import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {fixture,NodeConnection} from '../step1/sqlite-harness.mjs';
import {LocalDatabase,configureConnection} from '../../.expo/step1-tests/core/database/database.js';
import {ReconstructionRepository} from '../../.expo/step1-tests/features/reconstruction/repository.js';
import {reconstruct} from '../../.expo/step1-tests/services/reconstruction/rules.js';
import {TimelineRepository} from '../../.expo/step1-tests/features/timeline/repository.js';
import {RouteRepository} from '../../.expo/step1-tests/features/route/repository.js';
const photo=(local=null,gps=null,offset=null,id=randomUUID())=>({id,mediaId:randomUUID(),position:0,metadata:{exif:{},capture:local?{local,utc:offset===null?null:new Date(Date.parse(local+'Z')-offset*60000).toISOString(),offset_minutes:offset,precision:'second',source:'exif',warnings:[]}:null,gps,warnings:[]},parserVersion:1,dayId:null,stopId:null,filename:'synthetic.jpg',thumbnail:null});
const point={latitude:12.5,longitude:77.5};
const kinds=(r,k)=>r.proposals.filter(p=>p.kind===k);
test('timestamps deterministic, 6h gaps split; crossing midnight need not split',()=>{const a=photo('2001-02-03T23:30:00',null,330),b=photo('2001-02-04T01:00:00',null,330),c=photo('2001-02-07T12:00:00',null,330);const r=reconstruct([a,b,c]);assert.equal(kinds(r,'section').length,2);assert.deepEqual(r,reconstruct([c,b,a]));assert.equal(kinds(r,'section')[0].members.length,2);});
test('unknown/malformed/implausible timestamp stays ungrouped',()=>{for(const stamp of [null,'2001-02-30T01:00:00','1700-01-01T01:00:00']){const p=photo();if(stamp)p.metadata.capture={local:stamp,offset_minutes:null,utc:null};const r=reconstruct([p]);assert.deepEqual(r.unknown,[p.id]);assert.equal(r.proposals.length,0);}});
test('mixed offsets and floating clocks stay separate, tentative wording',()=>{const r=reconstruct([photo('2001-01-01T10:00:00',null,330),photo('2001-01-01T10:00:00',null,-300),photo('2001-01-01T10:00:00')]);assert.equal(kinds(r,'section').length,3);assert.ok(r.proposals.find(p=>p.zone==='Floating timezone').reasons.some(r=>r.includes('Wall-clock')));});
test('GPS contiguous A-B-A remains three visits; time breaks separate same place',()=>{const r=reconstruct([photo('2001-01-01T10:00:00',point,0),photo('2001-01-01T10:30:00',{latitude:15,longitude:77},0),photo('2001-01-01T11:00:00',point,0),photo('2001-01-01T14:00:00',point,0)]);assert.equal(kinds(r,'location').length,4);});
test('nearby GPS groups, no GPS breaks continuity, untimed GPS has no route order',()=>{const a=photo('2001-01-01T10:00:00',point,0),b=photo('2001-01-01T10:10:00',{latitude:12.5001,longitude:77.5001},0);assert.equal(kinds(reconstruct([a,b]),'location').length,1);const r=reconstruct([a,photo('2001-01-01T10:05:00',null,0),b,photo(null,point)]);assert.equal(kinds(r,'location').length,3);assert.ok(r.proposals.some(p=>p.reasons.includes('No chronology; no route order inferred')));});
test('missing/invalid GPS never becomes zero; real zero is flagged',()=>{const r=reconstruct([photo(null),photo(null,{latitude:999,longitude:0}),photo(null,{latitude:0,longitude:0})]);assert.equal(r.missingGps.length,2);assert.equal(kinds(r,'location').length,1);assert.match(r.proposals[0].reasons.join(),/Zero-coordinate/);});
async function setup(t){const f=await fixture(t);const trip=await f.trips.createTripDraft({title:'Reconstruction'});const repo=new ReconstructionRepository(f.database,f.vault.id,randomUUID);return {...f,trip,repo};}
async function seed(f,ps){for(const [index,p] of ps.entries()){p.position=index;await f.connection.runAsync(`INSERT INTO media(id,vault_id,sha256,byte_size,mime_type,extension,source_metadata_json,source_fidelity,parser_version,created_at,updated_at) VALUES(?,?,?,1,'image/jpeg','jpg',?,'unknown',1,?,?)`,p.mediaId,f.vault.id,p.mediaId.replaceAll('-','').repeat(2),JSON.stringify(p.metadata),'2001-01-01T00:00:00Z','2001-01-01T00:00:00Z');await f.connection.runAsync('INSERT INTO trip_media(id,vault_id,trip_id,media_id,position,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',p.id,f.vault.id,f.trip.id,p.mediaId,index,'2001-01-01T00:00:00Z','2001-01-01T00:00:00Z');}}
async function suggestions(f){return(await f.repo.list(f.trip.id)).filter(s=>s.kind!=='run');}
test('migration model, run snapshot and FK integrity',async t=>{const f=await setup(t);await seed(f,[photo('2001-01-01T10:00:00',point,0)]);await f.repo.run(f.trip.id);assert.equal((await suggestions(f)).length,2);assert.deepEqual(await f.connection.getAllAsync('PRAGMA foreign_key_check'),[]);await assert.rejects(f.connection.runAsync("UPDATE draft_suggestions SET evidence_json='{}'"),/immutable/);});
test('acceptance creates canonical entities transactionally; repeated acceptance/rerun is safe',async t=>{const f=await setup(t);await seed(f,[photo('2001-01-01T10:00:00',point,0),photo()]);const before=await f.connection.getAllAsync('SELECT * FROM media');await f.repo.run(f.trip.id);const ss=await suggestions(f),section=ss.find(s=>s.kind==='section'),location=ss.find(s=>s.kind==='location');await f.repo.edit(f.trip.id,section.id,'First morning');const a=await f.repo.accept(f.trip.id,section.id);assert.deepEqual(await f.repo.accept(f.trip.id,section.id),a);await assert.rejects(f.repo.accept(f.trip.id,location.id),/Confirm/);assert.equal((await f.connection.getAllAsync('SELECT * FROM places')).length,0);await f.repo.accept(f.trip.id,location.id,{confirmPlace:true,confirmAppend:true});await f.repo.run(f.trip.id);assert.equal((await f.connection.getAllAsync('SELECT * FROM trip_days')).length,1);assert.equal((await f.connection.getAllAsync('SELECT * FROM stops')).length,1);assert.deepEqual(await f.connection.getAllAsync('SELECT * FROM media'),before);});
test('reject persists without canonical edits and cannot be accepted later',async t=>{const f=await setup(t);await seed(f,[photo('2001-01-01T10:00:00')]);await f.repo.run(f.trip.id);const s=(await suggestions(f))[0];await f.repo.reject(f.trip.id,s.id);await f.repo.reject(f.trip.id,s.id);await f.repo.run(f.trip.id);await assert.rejects(f.repo.accept(f.trip.id,s.id),/rejected/);assert.equal((await f.connection.getAllAsync('SELECT * FROM trip_days')).length,0);});
test('explicit existing section/Place/Stop reuse preserves canonical fields/order',async t=>{const f=await setup(t);await seed(f,[photo('2001-01-01T10:00:00',point,0)]);const timeline=new TimelineRepository(f.database,f.vault.id,randomUUID);const day=await timeline.createTripDay(f.trip.id,{label:'User day'});const route=new RouteRepository(f.database,f.vault.id,randomUUID);const place=await route.createPlace({name:'User place'});const stop=await route.addStop(f.trip.id,{placeId:place.id});const before=await f.connection.getAllAsync('SELECT * FROM stops');await f.repo.run(f.trip.id);const ss=await suggestions(f);await f.repo.accept(f.trip.id,ss.find(s=>s.kind==='section').id,{dayId:day.id});await f.repo.accept(f.trip.id,ss.find(s=>s.kind==='location').id,{stopId:stop.id});assert.deepEqual(await f.connection.getAllAsync('SELECT * FROM stops'),before);assert.equal((await f.connection.getFirstAsync('SELECT label FROM trip_days')).label,'User day');});
test('conflicting assignment rolls back created canonical rows',async t=>{const f=await setup(t);const p=photo('2001-01-01T10:00:00');await seed(f,[p]);await f.repo.run(f.trip.id);const s=(await suggestions(f))[0];const timeline=new TimelineRepository(f.database,f.vault.id,randomUUID);const day=await timeline.createTripDay(f.trip.id,{label:'Existing'});await f.connection.runAsync('UPDATE trip_media SET day_id=?',day.id);await assert.rejects(f.repo.accept(f.trip.id,s.id),/another section/);assert.equal((await f.connection.getAllAsync('SELECT * FROM trip_days')).length,1);assert.equal((await suggestions(f))[0].state,'pending');});
test('trip/vault isolation and tombstoned trip reject operations',async t=>{const f=await setup(t);await seed(f,[photo('2001-01-01T10:00:00')]);await f.repo.run(f.trip.id);const s=(await suggestions(f))[0];const other=await f.trips.createTripDraft({title:'Other'});await assert.rejects(f.repo.accept(other.id,s.id));await assert.rejects(new ReconstructionRepository(f.database,randomUUID(),randomUUID).run(f.trip.id));await f.trips.trashTrip(f.trip.id);await assert.rejects(f.repo.run(f.trip.id));});
test('restart retains decisions and immutable input snapshots',async t=>{const f=await setup(t);await seed(f,[photo('2001-01-01T10:00:00')]);await f.repo.run(f.trip.id);const s=(await suggestions(f))[0];await f.repo.reject(f.trip.id,s.id);const before=await f.repo.list(f.trip.id);await f.database.close();const c=new NodeConnection(f.path);await configureConnection(c);try{assert.deepEqual(await new ReconstructionRepository(new LocalDatabase(c),f.vault.id,randomUUID).list(f.trip.id),before);}finally{await c.closeAsync();}});
test('membership edits reject foreign members, preserve evidence and allow excluded subset',async t=>{const f=await setup(t);await seed(f,[photo('2001-01-01T10:00:00'),photo('2001-01-01T11:00:00')]);await f.repo.run(f.trip.id);const s=(await suggestions(f))[0];await assert.rejects(f.repo.edit(f.trip.id,s.id,'X',[randomUUID()]));const member=JSON.parse(s.payload_json).members[0];await f.repo.edit(f.trip.id,s.id,'Renamed',[member]);assert.equal((await suggestions(f))[0].evidence_json,s.evidence_json);await f.repo.accept(f.trip.id,s.id);assert.equal((await f.connection.getAllAsync('SELECT * FROM trip_media WHERE day_id IS NOT NULL')).length,1);});
test('rapid GPS jumps are review warnings without invented routes',()=>{const r=reconstruct([photo('2001-01-01T10:00:00',point,0),photo('2001-01-01T10:10:00',{latitude:30,longitude:77},0)]);assert.ok(r.proposals.every(p=>p.reasons.some(r=>r.includes('Rapid GPS jump'))));});
test('overlapping older pending run cannot duplicate accepted objects',async t=>{const f=await setup(t);const a=photo('2001-01-01T10:00:00');await seed(f,[a]);await f.repo.run(f.trip.id);const old=(await suggestions(f))[0];await seed(f,[photo('2001-01-01T11:00:00')]);await f.repo.run(f.trip.id);const fresh=(await suggestions(f)).find(s=>s.id!==old.id);await f.repo.accept(f.trip.id,old.id);await assert.rejects(f.repo.accept(f.trip.id,fresh.id),/already have an accepted/);assert.equal((await f.connection.getAllAsync('SELECT * FROM trip_days')).length,1);});
test('clear/replace corrections are inputs, source evidence stays unchanged',async t=>{const f=await setup(t);const p=photo('2001-01-01T10:00:00',point,0);await seed(f,[p]);await f.connection.runAsync('UPDATE media SET capture_override_json=?,location_override_json=?',JSON.stringify({mode:'clear'}),JSON.stringify({mode:'replace',value:{latitude:20,longitude:30}}));await f.repo.run(f.trip.id);const ss=await suggestions(f);assert.equal(ss.length,1);assert.equal(ss[0].kind,'location');assert.deepEqual(JSON.parse(ss[0].payload_json).point,{latitude:20,longitude:30});assert.equal((await f.connection.getFirstAsync('SELECT source_metadata_json FROM media')).source_metadata_json,JSON.stringify(p.metadata));});
test('newly accepted Place/Stop is readable by existing route domain',async t=>{const f=await setup(t);await seed(f,[photo('2001-01-01T10:00:00',point,0)]);await f.repo.run(f.trip.id);const s=(await suggestions(f)).find(s=>s.kind==='location');await f.repo.accept(f.trip.id,s.id,{confirmPlace:true,confirmAppend:true});const route=new RouteRepository(f.database,f.vault.id,randomUUID);assert.equal((await route.getRoute(f.trip.id)).stops.length,1);assert.equal((await route.listPlaces()).length,1);});
test('forward provenance repair preserves complete development evidence',async t=>{const f=await setup(t);await seed(f,[photo('2001-01-01T10:00:00',point,0)]);await f.repo.run(f.trip.id);const s=(await suggestions(f)).find(s=>s.kind==='location');const accepted=await f.repo.accept(f.trip.id,s.id,{confirmPlace:true,confirmAppend:true});const old=JSON.stringify({suggestionId:s.id,algorithmVersion:1,rule:'250m photo cluster; user confirmed'});await f.connection.runAsync('UPDATE places SET provenance_json=? WHERE id=?',old,accepted.placeId);const {reconstructionProvenanceSchema}=await import('../../.expo/step1-tests/core/database/migrations/0007-reconstruction-provenance.js');await f.connection.execAsync(reconstructionProvenanceSchema);assert.equal((await new RouteRepository(f.database,f.vault.id,randomUUID).getPlace(accepted.placeId)).provenance.note,old);});
test('GPS does not bridge an intervening different-offset visit',()=>{const a=photo('2001-01-01T10:00:00',point,0),b=photo('2001-01-01T11:30:00',{latitude:13,longitude:77},60),c=photo('2001-01-01T11:00:00',point,0);assert.equal(kinds(reconstruct([a,b,c]),'location').length,3);b.metadata.gps=null;assert.equal(kinds(reconstruct([a,b,c]),'location').length,2);});
