// Deterministic synthetic corpus. plain.jpg is a generated 96x64 blue/red rectangle.
// No camera/private imagery. Remaining bytes are generated by this script.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { deflateSync } from 'node:zlib';
const dir=new URL('./',import.meta.url);
const jpeg=readFileSync(new URL('plain.jpg',dir));
const tiff=Buffer.alloc(2048);tiff.write('II');tiff.writeUInt16LE(42,2);tiff.writeUInt32LE(8,4);
let cursor=8;
function ifd(entries){const start=cursor;cursor+=2+entries.length*12+4;tiff.writeUInt16LE(entries.length,start);
 for(const [i,[tag,type,value]] of entries.entries()) {const p=start+2+i*12;tiff.writeUInt16LE(tag,p);tiff.writeUInt16LE(type,p+2);
  if(type===3){tiff.writeUInt32LE(1,p+4);tiff.writeUInt16LE(value,p+8);}
  else if(type===4){tiff.writeUInt32LE(1,p+4);tiff.writeUInt32LE(value,p+8);}
  else {const data=type===2?Buffer.from(value+'\0'):value;tiff.writeUInt32LE(type===5?data.length/8:data.length,p+4);
   if(data.length<=4)data.copy(tiff,p+8);else{tiff.writeUInt32LE(cursor,p+8);data.copy(tiff,cursor);cursor+=data.length;}}
 }return start;}
ifd([[0x112,3,6],[0x8769,4,0],[0x8825,4,0]]);
const exif=ifd([[0x9003,2,'2001:02:03 04:05:06'],[0x9011,2,'+05:30']]);tiff.writeUInt32LE(exif,8+2+12+8);
function rational(n){const b=Buffer.alloc(24);[n,30,0].forEach((v,i)=>{b.writeUInt32LE(v,i*8);b.writeUInt32LE(1,i*8+4);});return b;}
const gps=ifd([[1,2,'N'],[2,5,rational(12)],[3,2,'E'],[4,5,rational(77)]]);tiff.writeUInt32LE(gps,8+2+24+8);
const payload=Buffer.concat([Buffer.from('Exif\0\0'),tiff.subarray(0,cursor)]);const app=Buffer.alloc(4);app[0]=255;app[1]=225;app.writeUInt16BE(payload.length+2,2);
writeFileSync(new URL('capture-gps.jpg',dir),Buffer.concat([jpeg.subarray(0,2),app,payload,jpeg.subarray(2)]));
function crc(b){let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function chunk(name,data){const b=Buffer.alloc(12+data.length);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,8+data.length)),8+data.length);return b;}
const signature=Buffer.from([137,80,78,71,13,10,26,10]);const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(64);ihdr.writeUInt32BE(32,4);ihdr[8]=8;ihdr[9]=6;
const pixels=Buffer.alloc(32*(64*4+1));for(let y=0;y<32;y++)for(let x=0;x<64;x++){const p=y*257+1+x*4;pixels[p]=x*4;pixels[p+1]=120;pixels[p+2]=200;pixels[p+3]=x<32?100:255;}
const png=Buffer.concat([signature,chunk('IHDR',ihdr),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);writeFileSync(new URL('transparent.png',dir),png);
writeFileSync(new URL('animated.png',dir),Buffer.concat([signature,chunk('IHDR',ihdr),chunk('acTL',Buffer.from([0,0,0,2,0,0,0,0])),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]));
writeFileSync(new URL('truncated.jpg',dir),jpeg.subarray(0,100));
writeFileSync(new URL('unsupported.gif',dir),Buffer.from('GIF89a unsupported synthetic fixture'));
const empty={exif:{},capture:null,gps:null,warnings:[]};
const entries=[['plain.jpg','jpg',96,64,empty],['transparent.png','png',64,32,empty],['capture-gps.jpg','jpg',64,96,{exif:{DateTimeOriginal:'2001:02:03 04:05:06',OffsetTimeOriginal:'+05:30',Orientation:'6'},capture:{local:'2001-02-03T04:05:06',utc:'2001-02-02T22:35:06Z',offset_minutes:330,precision:'second',source:'exif',warnings:[]},gps:{latitude:12.5,longitude:77.5},warnings:[]}]];
const manifest=Object.fromEntries(entries.map(([name,ext,width,height,sourceMetadata])=>{const b=readFileSync(new URL(name,dir));return [name,{sha256:createHash('sha256').update(b).digest('hex'),byteSize:b.length,mimeType:ext==='jpg'?'image/jpeg':'image/png',extension:ext,width,height,sourceMetadata,parserVersion:1}];}));
writeFileSync(new URL('manifest.json',dir),JSON.stringify(manifest,null,2)+'\n');
